name=SensorRoxoOBR
version=1.0.0
author=Wesley Oliveira <wesleycooliveira@gmail.com>
maintainer=Wesley Oliveira <wesleycooliveira@gmail.com>
sentence=Facilita o uso do sensor de cor TCS34725 via multiplexador I2C para robôs da OBR.
paragraph=Desenvolvida para simplificar a programação de robôs de linha da OBR. Esta biblioteca gerencia o sensor TCS34725 integrado a um multiplexador I2C, automatizando a troca de canais, normalização de dados e calibração para a identificação direta de cores essenciais como verde, vermelho, preto e branco.
category=Sensors
url=https://github.com
architectures=*